import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { cn } from '@/lib/utils';
import { FilterProvider } from '@/lib/filter/useFilter';
import React from 'react';
import Navbar from '@/components/Navbar';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={'h-full bg-gray-100'}>
      <UserProvider>
        <FilterProvider>
          <body className={cn(inter.className, 'h-full antialiased')}>
            <div className="min-h-full">
              <Navbar />
              <div className="py-10">
                <Header />
                <main>
                  <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
                    {children}
                  </div>
                </main>
              </div>
            </div>
          </body>
        </FilterProvider>
      </UserProvider>
    </html>
  );
}
